# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  -
    # ID of the build
    id: "ceres"

    main: ./main.go
    binary: inspektor

    env:
      - CGO_ENABLED=0

    goos:
      - windows
      - linux
      - darwin

    goarch:
      - amd64
    
  - main: ./utils/skeleton.go
    binary: skull

    env:
      - CGO_ENABLED=0

    goos:
      - windows
      - linux
      - darwin

    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      format: zip
